config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :inventories
  resources :categories
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product

  enum status: {draft: 0, published: 1}

  validates_presence_of  :color, :size, :quantity, :price

  monetize :price_cents

  mount_uploader :image, InventoryUploader
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /inventories or /inventories.json
  def index  
    if logged_in?(:site_admin)
      @inventories = Inventory.all
    else
      @inventories = Inventory.published
    end    
  end

  # GET /inventories/1 or /inventories/1.json
  def show
    if logged_in?(:site_admin) == false && @inventory.draft?
      redirect_to product_path(@inventory.product_id), notice: 'You are not authorized to view this page!' 
    end
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
    @inventory.product_id= params[:product_id]
    @product_title = Product.find(@inventory.product_id).title
  end

  # GET /inventories/1/edit
  def edit
    @product_title = Product.find(@inventory.product_id).title
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    @product_title = Product.find(@inventory.product_id).title

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to product_path(@inventory.product_id), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    @product_title = Product.find(@inventory.product_id).title

    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to product_path(@inventory.product_id), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy

    #To remove images from s3
    @inventory.image.remove!

    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:color, :size, :quantity, :product_id, :price, :image, :status)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<div class='form'>
  <%= form_with(model: @inventory) do |form| %>
    <% if @inventory.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

        <ul>
          <% @inventory.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-text-field'>
      <%= form.label :color, style: "display: block" %>
      <%= form.text_field :color %>
    </div>

    <div class='form-text-field'>
      <%= form.label :size, style: "display: block" %>
      <%= form.text_field :size %>
    </div>

    <div class='form-text-field'>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.text_field :quantity %>
    </div>

    <div class='form-price'>
      <%= form.label :price, style: "display: block" %>
      $ <%= form.text_field :price %>
    </div>

     <br>

    <div class=''>
      <div>
        <%= form.radio_button :status, 'draft' %>
        <%= form.label :status, 'Draft' %>
      </div>
      <br>
      <div>
        <%= form.radio_button :status, 'published' %>
        <%= form.label :status, 'Published' %>
      </div>
    </div>

    <div class='form-text-field'>
      <%= form.label :image, style: "display: block" %>
      <br>
      <h5>Current image</h5> 
      <% if @inventory.image.url %>
        <%= image_tag @inventory.image.url %>
      <% else %>
        No current image
      <% end %>
      <%= form.file_field :image %>
    </div>

    <div>
      <%= form.label :product, style: "display: block" %>
      <%= form.text_field :product_id, :value => @product_title, :readonly => true %>
      <%= form.hidden_field :product_id, value: inventory.product_id=%>
    </div>

    <div class='form-button'>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/inventories/_inventory.html.erb
<% if inventory.published?|| logged_in?(:site_admin) %>
  <div id="<%= dom_id inventory %>" class='inventory_card'>

    <%= image_tag check_image(inventory.image.url), size: "350x200" %>

    <br>
    <br>

    <p>
      <strong>Color:</strong>
      <%= inventory.color %>
    </p>

    <br>

    <p>
      <strong>Size:</strong>
      <%= inventory.size %>
    </p>

    <br>

    <p>
      <strong>Left in stock:</strong>
      <%= inventory.quantity %>
    </p>

    <br>

    <p>
      <strong>Price:</strong>
      $<%= inventory.price %>
    </p>

    <br>

    <div class='admin-link' >
      <%= link_to "Edit this inventory", edit_inventory_path(inventory) if logged_in?(:site_admin) %> 
    </div>
  </div>
  <% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= button_to "Destroy this inventory", @inventory, class: 'destroy-link' , method: :delete if logged_in?(:site_admin) %>
</div>

<br>

<div class='admin-link'>
  <%= link_to "Back to #{@product_title}", product_path(@inventory.product_id.to_i) %>
</div>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventories</h1>

<div class="inventories">
  <% @inventories.each do |inventory| %>
    <%= render inventory %>
  <% end %>
</div>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div class='admin-link'>
  <%= link_to "Back to #{@product_title}", product_path(@inventory.product_id.to_i) %>

  <br>
  <br>

  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Back to inventories", inventories_path %> |
  <%= link_to "Show this Inventory's Product", product_path(@inventory.product_id) %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete if logged_in?(:site_admin) %>
</div>