config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :inventories
  resources :categories
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  enum status: {draft: 0, published: 1}

  has_rich_text :description

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of  :title

  def image
    image = nil
    catch :done do 
      self.products.each do |product|
        product.inventories.each do |inventory|
          if inventory.image.url
            image = inventory.image.url
            throw :done
          end
        end
      end
    end
    
    return image
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /categories or /categories.json
  def index
    if logged_in?(:site_admin)
      @categories = Category.all
    else
      @categories = Category.published
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    if logged_in?(:site_admin) == false && @category.draft?
      redirect_to root_path, notice: 'You are not authorized to view this page!' 
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :description, :status)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">

  <div class='category-description'>
    <%= category.description %>
  </div>

</div>

app/views/categories/_form.html.erb
<div class='form'>
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-text-field'>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div class='form-text-area'>
      <%= form.label :description, style: "display: block" %>
      <%= form.rich_text_area :description %>
    </div>

    <br>

    <div class=''>
      <div>
        <%= form.radio_button :status, 'draft' %>
        <%= form.label :status, 'Draft' %>
      </div>
      <br>
      <div>
        <%= form.radio_button :status, 'published' %>
        <%= form.label :status, 'Published' %>
      </div>
    </div>

    <div class='form-button'>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<div class='content-container'>
  <div class='content'>
    <h1>Editing <%= @category.title %></h1>

    <%= render "form", category: @category %>

    <br>

    <%= button_to "Destroy this category", @category, class:'destroy-link', method: :delete if logged_in?(:site_admin) %>

    <br>
    
    <div class='admin-link'>
      <%= link_to "Back to #{@category.title}", @category %> |
      <%= link_to "Back to home", categories_path %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class='home-container'>
  <p style="color: green"><%= notice %></p>

  <div class='home-element' >
    <%= render 'shared/home_banner' %>
  </div>

  <% if logged_in?(:site_admin) %>
    <div class='home-element admin-link'>
      <%= link_to "New category", new_category_path, class: "admin-link" %>
    </div>
    <br />
  <% end -%>


  <div class='home-element'>
    <div id="categories">
      <% @categories.each do |category| %>
        <%= link_to category do %>
          <div class='category-card'>
            <div class='category-card-title'> 
              <%= category.title %>
            </div>
            <%= image_tag(check_image(category.image), size: "350x200")  %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div class='breadcrumb-nav'>
  <%= link_to 'Home', root_path %> > <%= @category.title %>
</div>

<%= render @category %>

<div class='admin-link'>
  <%= link_to "Add Product", new_product_path(:category_id => @category.id) if logged_in?(:site_admin) %>
</div>

<br>

<div class='category-products-container'>     
  <% @category.products.each do |product| %>
    <% if product.published? || logged_in?(:site_admin) %>
      <div class='category-products'>
        <%= link_to product do %>
          <div class='product-link-title'>
            <%= product.title %>
          </div>
          <%= image_tag(check_image(product.image), size: "350x200")  %>
        <% end %>
      </div>
      <% end %>
  <% end %>
</div>

<br>

<div class='bottom-links'>
  <%= link_to "Edit this category", edit_category_path(@category) if logged_in?(:site_admin) %> 
  <% if logged_in?(:site_admin) %> | <% end %>
  <%= link_to "Back to Home", categories_path %>
</div>