config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :inventories
  resources :categories
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :inventories, dependent: :destroy

  enum status: {draft: 0, published: 1}

  has_rich_text :description
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of  :title, :category_id

  def image
    image = nil
    catch :done do 
      self.inventories.each do |inventory|
        if inventory.image.url
          image = inventory.image.url
          throw :done
        end
      end
    end
    
    return image
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy get_display_image]
  before_action :get_inventories, only: %i[ show get_display_image ]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /products or /products.json
  def index
    if logged_in?(:site_admin)
      @products = Product.all
    else
      @products = Product.published
    end
  end

  # GET /products/1 or /products/1.json
  def show
    if logged_in?(:site_admin) || @product.published?
      @product = Product.includes(:inventories).friendly.find(params[:id])
      @inventory = Inventory.new
    else
      redirect_to product_path, notice: 'You are not authorized to view this page!' 
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.category_id = params[:category_id]
    @category_title = Category.find(@product.category_id).title
  end

  # GET /products/1/edit
  def edit
    @category_title = Category.find(@product.category_id).title
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @category_title = Category.find(@product.category_id).title

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        # format.html { render :new, :locals => {category_id:params[:category_id], category_title: params[:category_title]}, status: :unprocessable_entity }
        # flash[:error]
        format.html { render :new, status: :unprocessable_entity }
        # format.html { redirect_to new_product_path, flash[:error] => @product.errors.full_messages.join(', '), status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @category_title = Category.find(@product.category_id).title
    
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def get_inventories
      @inventories = Inventory.where(product_id: @product.id)
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :category_id, :status)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.erb
<div class='form'>
  <% if Category.any? %>
    <%= form_with(model: product) do |form| %>
      <% if product.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-text-field'>
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
      </div>

      <div class='form-text-area'>
        <%= form.label :description, style: "display: block" %>
        <%= form.rich_text_area :description %>
      </div>

      <div class='form-product-inputs'>
 <!--        <div class='form-price'>
          <%= form.label :price, style: "display: block" %>
          <%= form.text_field :price %>
        </div> -->

      <div class='form-dropdown'>
        <%= form.label :category, style: "display: block" %>
        <%= form.text_field :category_id, :value => @category_title, :readonly => true %>
        <%= form.hidden_field :category_id, value: product.category_id %>
      </div>

    <!--     <div class='form-dropdown'>
          <%= form.label :category, style: "display: block" %>
          <%= form.select :category_id, options_from_collection_for_select(Category.all, 'id', 'title', params[:category_id]) %>
        </div> -->
      </div>

      <br>

      <div class=''>
        <div>
          <%= form.radio_button :status, 'draft' %>
          <%= form.label :status, 'Draft' %>
        </div>
        <br>
        <div>
          <%= form.radio_button :status, 'published' %>
          <%= form.label :status, 'Published' %>
        </div>
      </div>

      <!--  -->

      <div class='form-button'>
        <%= form.submit %>
      </div>

    <% end %>
  <% else %>

        <%= link_to 'You need to create a category first', new_category_path %>
        
  <% end %>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <%= product.description %>
  </p>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<%= button_to "Destroy this product", @product, class: 'destroy-link ', method: :delete if logged_in?(:site_admin) %>

<br>

<div class='admin-link'>
  <%= link_to "Back to #{@product.title}", @product %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class='breadcrumb-nav'>
  <%= link_to 'Home', root_path %> > All Products
</div>

<!-- <div class="products-container">
  <% @products.each do |product| %>
    <% if product.published? || logged_in?(:site_admin) %>
        <%= link_to product do %>
          <div class='products'>
            <%= product.title %>
            <%= product.description %>
            <%= image_tag(check_image(product.image), size: "350x200")  %>
          </div>
        <% end %>
      <% end %>
  <% end %>
</div> -->

<div class='category-products-container'>     
  <% @products.each do |product| %>
    <% if product.published? || logged_in?(:site_admin) %>
      <div class='category-products'>
        <%= link_to product do %>
          <div class='product-link-title'>
            <%= product.title %>
          </div>
          <%= image_tag(check_image(product.image), size: "350x200")  %>
        <% end %>
      </div>
      <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to #{@category_title}", category_path(@product.category_id.to_i) %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<div class='breadcrumb-nav'>
  <%= link_to 'Home', root_path %> > 
  <%= link_to @product.category.title, category_path(@product.category.id) %> > 
  <%= @product.title %>
</div>

<%= image_tag check_image(@product.image), size: "350x200" %>

<br>

<%= render @product %>

<br>

<div class='admin-link'>
  <%= link_to "Edit this product", edit_product_path(@product) if logged_in?(:site_admin) %>
</div>

<br>

<div class='admin-link'>
  <%= link_to "Add Inventory", new_inventory_path(:product_id => @product.id) if logged_in?(:site_admin) %>
</div>

<br>

<div>


  <div class="inventories">
    <%= render @inventories %>
  </div>
</div>